In [1]:
%load_ext pycodestyle_magic
# %%pycodestyle


In [50]:
import pandas as pd
import numpy as np
import shap
from pandasql import sqldf
from sklearn.linear_model import LinearRegression
from xgboost import XGBRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.datasets import load_boston



# Lambdas

def q(x):
    return sqldf(x, globals())

# Randomize given the value options


def randomize_value_choice(value_options):
    """
    The value_options format is either:
        [True, False] - True or False
        [1,2,3,4,5] - 1 to 5
        [[0,1,4],5] - Any subset of [0,1,2,3,4] and 5
            represents the number of features in the dataframe
    """
    value = None
    # Check to make sure there are value options
    if len(value_options) > 0:
        # Make sure it isn't a 2D List
        if type(value_options[0]) != list:
            # Simple choice from the list -
                # In the future this might include a distribution mean+std
            np.random.choice(value_options)
        else:
            # If the option is a 2D array it means we take
                # each element with 50% probability
            value = []
            for element in value_options[0]:
                random_number = np.random.rand(1)[0]
                if random_number > 0.5:
                    value.append(element)
    return value

# My own version of RandomizedSearchCV


def RandomizedGridSearchCV(n_experiments, pipe,
                           param_distributions, train_X, train_y,
                           test_X, test_y,
                           scoring='neg_mean_squared_error', cv=2):
    train_X = train_X.copy()
    train_y = train_y.copy()
    test_X = test_X.copy()
    test_y = test_y.copy()

    # Transform the param_distributions into four arrays
    key_list = []
    transform_class_list = []
    parameter_name_list = []
    value_options_list = []
    for key, value_options in param_distributions.items():
        class_key, parameter_name = key.split("__")
        transform_class = pipe.named_steps[class_key]
        key_list.append(key)
        transform_class_list.append(transform_class)
        parameter_name_list.append(parameter_name)
        value_options_list.append(value_options)

    # Initialize experiments dictionary
    experiments = {}
    for key, transform_class, parameter_name, value_options in \
        zip(key_list, transform_class_list, parameter_name_list,
            value_options_list):
        if type(value_options[0]) != list:
            experiments[key] = []          
        else:
            # value_options[1] is the number of features
            for i in range(value_options[1]):
                experiments[key + "_" + str(i)] = []
    experiments['score'] = []

    # Iterate over the experiments
    for iteration in range(n_experiments):
        print("Iteration: ", iteration)

        # Updates the transform parameters
        for key, transform_class, parameter_name, value_options in \
            zip(key_list, transform_class_list, parameter_name_list,
                value_options_list):

            # Get the random value
            value = randomize_value_choice(value_options)

            # Set the value
            setattr(transform_class, parameter_name, value)

            # If the value option is a 2D array it is treated differently
            if type(value_options[0]) != list:
                experiments[key].append(value)             
            else:
                for i in range(value_options[1]):
                    result_value = True if i in list(value) else False
                    experiments[key + "_" + str(i)].append(result_value)
                    
        # Fit
        pipe.fit(train_X, train_y)
        
        # Predict
        pred_y = pipe.predict(test_X)
        
        print(pipe)
        print(pred_y[0:5])
        
        # Scoring
        if scoring == 'neg_mean_squared_error':
            score = mean_squared_error(pred_y, test_y)
        else:
            raise Exception('Scoring type not implemented')
        
        # Appending the score
        experiments["score"].append(score)

    experiments_df = pd.DataFrame(experiments)
    return experiments_df

# Standard scaler data preparation class


class StandardScalerTransform(BaseEstimator, TransformerMixin):
    def __init__(self, column_indices_to_replace=[]):
        self.column_indices_to_replace = column_indices_to_replace
        self.standard_scalers = {}
        

    def fit(self, X, y=None):
        for index in self.column_indices_to_replace:
            self.standard_scalers[index] = StandardScaler()
            self.standard_scalers[index].fit(X[:, index:index+1])
        return self

    def transform(self, X, y=None):
        for index in self.column_indices_to_replace:
            X[:, index:index+1] = self.standard_scalers[index].transform(X[:, index:index+1])
        print(X)
        return np.c_[X]

# Min-max scaler data preparation class


class MinMaxScalerTransform(BaseEstimator, TransformerMixin):
    def __init__(self, column_indices_to_replace=[]):
        self.column_indices_to_replace = column_indices_to_replace
        self.min_max_scalers = {}

    def fit(self, X, y=None):
        for index in self.column_indices_to_replace:
            self.min_max_scalers[index] = MinMaxScaler()
            self.min_max_scalers[index].fit(X[:, index:index+1])
        return self

    def transform(self, X, y=None):
        for index in self.column_indices_to_replace:
            X[:, index:index+1] = self.min_max_scalers[index].transform(X[:, index:index+1])
        print(X)
        return np.c_[X]

# Generic xgboost fit using several grid searches


def get_xgboost_model(train_X, train_y):
    model = Pipeline([('xgb', XGBRegressor())])

    # 1) Tune max depth
    param_grid = [{
        'xgb__n_estimators': [100],
        'xgb__learning_rate': [0.1],
        'xgb__max_depth': [1, 2, 4, 6, 8],
        'xgb__subsample': [1.00]
    }]
    gs1 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs1 = gs1.fit(train_X, train_y)
    max_depth = gs1.best_params_['xgb__max_depth']
    # print(gs1.best_score_)
    # print(gs1.best_params_)

    # 2) Tune subsample
    param_grid = [{
        'xgb__n_estimators': [100],
        'xgb__learning_rate': [0.1],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [0.30, 0.40, 0.50, 0.60, 0.70, 0.80, 0.90, 1.00]
    }]
    gs2 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs2 = gs2.fit(train_X, train_y)
    subsample = gs2.best_params_['xgb__subsample']
    # print(gs2.best_score_)
    # print(gs2.best_params_)

    # 3) Tune n_estimators
    param_grid = [{
        'xgb__n_estimators': [50, 100, 150, 200],
        'xgb__learning_rate': [0.1],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample]
    }]
    gs3 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs3 = gs3.fit(train_X, train_y)
    n_estimators = gs3.best_params_['xgb__n_estimators']
    # print(gs3.best_score_)
    # print(gs3.best_params_)

    # 4) Tune learning rate
    param_grid = [{
        'xgb__n_estimators': [n_estimators],
        'xgb__learning_rate': [0.1],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample]
    },
        {
        'xgb__n_estimators': [n_estimators * 3],
        'xgb__learning_rate': [0.03],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample]
    }]
    gs4 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs4 = gs4.fit(train_X, train_y)
    n_estimators = gs4.best_params_['xgb__n_estimators']
    learning_rate = gs4.best_params_['xgb__learning_rate']
    # print(gs4.best_score_)
    # print(gs4.best_params_)

    # 5) Tune n_estimators
    param_grid = [{
        'xgb__n_estimators': [
            int(0.8 * n_estimators),
            int(1.0 * n_estimators),
            int(1.2 * n_estimators)
        ],
        'xgb__learning_rate': [learning_rate],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample]
    }]
    gs5 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs5 = gs5.fit(train_X, train_y)
    n_estimators = gs5.best_params_['xgb__n_estimators']
    # print(gs5.best_score_)
    # print(gs5.best_params_)

    # 6) Tune sampling by tree
    param_grid = [{
        'xgb__n_estimators': [n_estimators],
        'xgb__learning_rate': [learning_rate],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample],
        'xgb__colsample_bytree': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
        'xgb__colsample_bylevel': [1.0]
    }]
    gs6 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs6 = gs6.fit(train_X, train_y)
    colsample_bytree = gs6.best_params_['xgb__colsample_bytree']
    # print(gs6.best_score_)
    # print(gs6.best_params_)

    # 7) Tune subsample
    param_grid = [{
        'xgb__n_estimators': [n_estimators],
        'xgb__learning_rate': [learning_rate],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
        'xgb__colsample_bytree': [colsample_bytree],
        'xgb__colsample_bylevel': [1.0]
    }]
    gs7 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs7 = gs7.fit(train_X, train_y)
    subsample = gs7.best_params_['xgb__subsample']
    # print(gs7.best_score_)
    # print(gs7.best_params_)

    # 8) Tune sampling by level
    n_estimators = gs7.best_params_['xgb__n_estimators']
    param_grid = [{
        'xgb__n_estimators': [n_estimators],
        'xgb__learning_rate': [learning_rate],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample],
        'xgb__colsample_bytree': [colsample_bytree],
        'xgb__colsample_bylevel': [0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    }]
    gs8 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs8 = gs8.fit(train_X, train_y)
    colsample_bylevel = gs8.best_params_['xgb__colsample_bylevel']
    # print(gs8.best_score_)
    # print(gs8.best_params_)

    # 9) Tune sampling fields
    n_estimators = gs8.best_params_['xgb__n_estimators']
    subsample = 0.9 if subsample == 1.0 else subsample
    colsample_bytree = 0.6 if colsample_bytree == 0.5 else colsample_bytree
    colsample_bylevel = 0.9 if colsample_bylevel == 1.0 else colsample_bylevel
    param_grid = [{
        'xgb__n_estimators': [n_estimators],
        'xgb__learning_rate': [learning_rate],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample, subsample + 0.1],
        'xgb__colsample_bytree': [colsample_bytree - 0.1, colsample_bytree],
        'xgb__colsample_bylevel': [colsample_bylevel, colsample_bylevel + 0.1]
    }]
    gs9 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs9 = gs9.fit(train_X, train_y)
    subsample = gs9.best_params_['xgb__subsample']
    colsample_bytree = gs9.best_params_['xgb__colsample_bytree']
    colsample_bylevel = gs9.best_params_['xgb__colsample_bylevel']
    # print(gs9.best_score_)
    # print(gs9.best_params_)

    # 10) Tune alpha
    param_grid = [{
        'xgb__n_estimators': [n_estimators],
        'xgb__learning_rate': [learning_rate],
        'xgb__max_depth': [max_depth],
        'xgb__subsample': [subsample],
        'xgb__colsample_bytree': [colsample_bytree],
        'xgb__colsample_bylevel': [colsample_bylevel],
        'xgb__reg_lambda': [0.001, 0.01, 0.1, 0.3, 1, 3, 10, 100, 1000]
    }]
    gs10 = GridSearchCV(
        estimator=model,
        param_grid=param_grid,
        scoring='neg_mean_squared_error',
        cv=2)
    gs10 = gs10.fit(train_X, train_y)
    # print(gs10.best_score_)
    # print(gs10.best_params_)

    # Find the best model
    # Sometimes the best model isn't the last one, so checking all of them
    best_model = gs1
    best_model_score = gs1.best_score_
    if gs2.best_score_ > best_model_score:
        best_model = gs2
        best_model_score = gs2.best_score_
    if gs2.best_score_ > best_model_score:
        best_model = gs2
        best_model_score = gs2.best_score_
    if gs3.best_score_ > best_model_score:
        best_model = gs3
        best_model_score = gs3.best_score_
    if gs4.best_score_ > best_model_score:
        best_model = gs4
        best_model_score = gs4.best_score_
    if gs5.best_score_ > best_model_score:
        best_model = gs5
        best_model_score = gs5.best_score_
    if gs6.best_score_ > best_model_score:
        best_model = gs6
        best_model_score = gs6.best_score_
    if gs7.best_score_ > best_model_score:
        best_model = gs7
        best_model_score = gs7.best_score_
    if gs8.best_score_ > best_model_score:
        best_model = gs8
        best_model_score = gs8.best_score_
    if gs9.best_score_ > best_model_score:
        best_model = gs9
        best_model_score = gs9.best_score_
    if gs10.best_score_ > best_model_score:
        best_model = gs10
        best_model_score = gs10.best_score_

    # Return the best model
    return XGBRegressor(**best_model.best_params_)

In [44]:
# standard_scalers

In [45]:
# min_max_scalers = {}
# column_indices_to_replace = [0,1]
# X = pd.DataFrame(boston_data['data']).values[:,0:3]
# for index in column_indices_to_replace:
#     min_max_scalers[index] = MinMaxScaler()
#     min_max_scalers[index].fit(X[:, index:index+1])

# for index in column_indices_to_replace:
#     print(min_max_scalers[index].transform(X[:, index:index+1]).flatten())
#     X[:, index:index+1] = min_max_scalers[index].transform(X[:, index:index+1])
# X    

In [46]:
# Example dataset
boston_data = load_boston()

X = pd.DataFrame(boston_data['data']).copy().values[:,0:3]
y = pd.DataFrame(boston_data['target']).copy().values
X = MinMaxScalerTransform([0]).fit_transform(X)
linear_regression = LinearRegression()
linear_regression.fit(X, y)
linear_regression.predict(X)
X

[[0.00000000e+00 1.80000000e+01 2.31000000e+00]
 [2.35922539e-04 0.00000000e+00 7.07000000e+00]
 [2.35697744e-04 0.00000000e+00 7.07000000e+00]
 ...
 [6.11892474e-04 0.00000000e+00 1.19300000e+01]
 [1.16072990e-03 0.00000000e+00 1.19300000e+01]
 [4.61841693e-04 0.00000000e+00 1.19300000e+01]]


array([[0.00000000e+00, 1.80000000e+01, 2.31000000e+00],
       [2.35922539e-04, 0.00000000e+00, 7.07000000e+00],
       [2.35697744e-04, 0.00000000e+00, 7.07000000e+00],
       ...,
       [6.11892474e-04, 0.00000000e+00, 1.19300000e+01],
       [1.16072990e-03, 0.00000000e+00, 1.19300000e+01],
       [4.61841693e-04, 0.00000000e+00, 1.19300000e+01]])

In [47]:
# Example dataset
boston_data = load_boston()

X = pd.DataFrame(boston_data['data']).copy().values[:,0:3]
y = pd.DataFrame(boston_data['target']).copy().values
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.20, random_state=42)
train_X, test_X = train_X, test_X
train_y, test_y = train_y.reshape(-1, 1), test_y.reshape(-1, 1)

scaler = StandardScaler()
train_X = scaler.fit_transform(train_X)
test_X = scaler.transform(test_X)
linear_regression = LinearRegression()
linear_regression.fit(train_X, train_y)
pred_y = linear_regression.predict(test_X)
pred_y[0:5]


array([[26.36416036],
       [26.70444347],
       [15.70090959],
       [23.32237206],
       [18.8339315 ]])

In [48]:
# Example dataset
boston_data = load_boston()

X = pd.DataFrame(boston_data['data']).copy().values[:,0:3]
y = pd.DataFrame(boston_data['target']).copy().values
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.20, random_state=42)
train_X, test_X = train_X, test_X
train_y, test_y = train_y.reshape(-1, 1), test_y.reshape(-1, 1)

linear_regression = LinearRegression(normalize=False)
linear_regression.fit(train_X, train_y)
pred_y = linear_regression.predict(test_X)
pred_y[0:5]


array([[26.36416036],
       [26.70444347],
       [15.70090959],
       [23.32237206],
       [18.8339315 ]])

In [51]:
# Example dataset
boston_data = load_boston()

# Extract pandas dataframe and target
X = pd.DataFrame(boston_data['data']).copy().values
y = pd.DataFrame(boston_data['target']).copy().values

# Train/test split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.20, random_state=42)
train_X, test_X = train_X, test_X
train_y, test_y = train_y.reshape(-1, 1), test_y.reshape(-1, 1)

# An okay model fit to the data
# xgb_model = get_xgboost_model(train_X, train_y)
linear_regression = LinearRegression(normalize=False)

# Pipeline
pipe = Pipeline([('standard_scaler', StandardScalerTransform()),
                 ('min_max_scaler', MinMaxScalerTransform()),
                 ('model', linear_regression)])

# Find the number of features
num_features = train_X.shape[1]

# Testing with these indices
indices = list(range(num_features))

# Possible configurations
param_distributions = {
    'standard_scaler__column_indices_to_replace': [indices, num_features],
    'min_max_scaler__column_indices_to_replace': [indices, num_features]
}

# Randomly search the space n_iter times
experiments_df = RandomizedGridSearchCV(
    n_experiments=10,
    pipe=pipe,
    param_distributions=param_distributions,
    train_X=train_X,
    train_y=train_y,
    test_X=test_X,
    test_y=test_y,
    scoring='neg_mean_squared_error',
    cv=2)

# Sort the scores
experiments_df.sort_values(by=['score'], ascending=False, inplace=True)

# Drop score
experiments_X_df = experiments_df.drop(['score'], axis=1)

# Get column names
X_column_names = experiments_X_df.columns

# Convert to numpy
experiments_X = experiments_X_df.values
experiments_y = experiments_df[['score']].values

# Create an XGBoost model tuned with the experiments data
xgb_experiments_model = get_xgboost_model(experiments_X, experiments_y)

# Fit the model
xgb_experiments_model.fit(experiments_X_df, experiments_y)

# Extract shap values
explainer = shap.TreeExplainer(xgb_experiments_model)
shap_values = explainer.shap_values(experiments_X_df)

# Shap as dataframe
pandas_shap_df = pd.DataFrame(shap_values, columns=X_column_names)
pandas_shap_df


Iteration:  0
[[ 1.28770177 -0.50032012 18.1        ... 20.2        -0.07433689
  24.91      ]
 [-0.33638447 -0.50032012  8.14       ... 21.          0.4301838
   8.47      ]
 [-0.40325332  1.01327135  6.06       ... 16.9         0.06529747
   7.83      ]
 ...
 [-0.40547014  2.95931752  2.01       ... 17.          0.37901005
   5.99      ]
 [ 0.85189733 -0.50032012 18.1        ... 20.2        -2.69458597
  23.27      ]
 [-0.38135592 -0.50032012  8.56       ... 20.9        -3.12158061
  10.63      ]]
[[ 1.28770177  0.          0.64296296 ...  0.80851064 -0.07433689
   0.63962472]
 [-0.33638447  0.          0.27407407 ...  0.89361702  0.4301838
   0.18598234]
 [-0.40325332  0.35        0.19703704 ...  0.45744681  0.06529747
   0.1683223 ]
 ...
 [-0.40547014  0.8         0.04703704 ...  0.46808511  0.37901005
   0.11754967]
 [ 0.85189733  0.          0.64296296 ...  0.80851064 -2.69458597
   0.59437086]
 [-0.38135592  0.          0.28962963 ...  0.88297872 -3.12158061
   0.24558499]]
[[-0

standard_scaler__column_indices_to_replace_0  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_1  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_2  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_3  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_4  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_5  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_6  \
0                                           0.0   
1                                           0.0   
2                                           0.0   
3                                           0.0   
4                                           0.0   
5                                           0.0   
6                                           0.0   
7                                           0.0   
8                                           0.0   
9                                           0.0   

   standard_scaler__column_indices_to_replace_7  \
0                 

In [41]:
xgb_experiments_model

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1, xgb__colsample_bylevel=0.5,
       xgb__colsample_bytree=0.5, xgb__learning_rate=0.1, xgb__max_depth=1,
       xgb__n_estimators=200, xgb__reg_lambda=0.001, xgb__subsample=0.6)

In [42]:
experiments_df

standard_scaler__column_indices_to_replace_0  \
6                                         False   
7                                         False   
1                                         False   
4                                         False   
9                                         False   
3                                          True   
8                                          True   
2                                          True   
5                                         False   
0                                          True   

   standard_scaler__column_indices_to_replace_1  \
6                                          True   
7                                          True   
1                                          True   
4                                          True   
9                                          True   
3                                         False   
8                                          True   
2                                          True   
5                                          True   
0                                          True   

   standard_scaler__column_indices_to_replace_2  \
6                                         False   
7                                          True   
1                                          True   
4                                         False   
9                                         False   
3                                         False   
8                                         False   
2                                         False   
5                                          True   
0                                          True   

   standard_scaler__column_indices_to_replace_3  \
6                                          True   
7                                         False   
1                                          True   
4                                          True   
9                                          True   
3                                         False   
8                                          True   
2                                          True   
5                                         False   
0                                          True   

   standard_scaler__column_indices_to_replace_4  \
6                                         False   
7                                          True   
1                                          True   
4                                          True   
9                                         False   
3                                         False   
8                                         False   
2                                          True   
5                                         False   
0                                          True   

   standard_scaler__column_indices_to_replace_5  \
6                                         False   
7                                          True   
1                                         False   
4                                         False   
9                                         False   
3                                         False   
8                                         False   
2                                          True   
5                                          True   
0                                         False   

   standard_scaler__column_indices_to_replace_6  \
6                                          True   
7                                          True   
1                                          True   
4                                          True   
9                                         False   
3                                         False   
8                                          True   
2                                          True   
5                                         False   
0                                         False   

   standard_scaler__column_indices_to_replace_7  \
6                 

In [10]:
# Transformation to polarized groups of shap values
polarized_shap_df = pandas_shap_df.copy()
for i in range(0, len(pandas_shap_df.index)):
    for j in range(0, len(pandas_shap_df.columns)):
        if not experiments_df.iloc[i, j]:
            polarized_df.iloc[i, j] = -1 * pandas_shap_df.iloc[i, j]
polarized_df


NameError: name 'polarized_df' is not defined

In [ ]:
# Certainly, I set a feature to True for large positive values
# Also, I set a feature to False for large negative values
# Otherwise, it is set to True or False
polarized_shap_result = polarized_df.sum()
polarized_shap_result
